name = "zemperica-api"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "SUGGESTIONS"
id = "7b06eef1f6864a22a7550533e92eaa17"

[vars]
BLOG_ORIGIN = "https://zemperica.jedai.space"
TELEGRAM_BOT_TOKEN = "8288769848:AAHLNHtSZNkyWP4wLvNMl6Xw1Gd0En1BDZc"
TELEGRAM_CHAT_ID = "2139255040"
N8N_WEBHOOK_URL = "https://n8n.jedai.space/webhook/k9RzYLOccAaPRcsK/webhook/zemperica-suggestion"
N8N_WEBHOOK_AUTH = "c2FibzpmRUxscWRvazBoY0hHd1BKOUxoeQ=="
